PostgreSQL:
  image: "postgres:latest"
  ports:
    - "5432:5432"
  expose:
    - "5432"
  environment:
    - "POSTGRES_USER=pgr"
    - "POSTGRES_PASSWORD=pgr"
    - "POSTGRES_DB=default"
  links:
    - Data:Data
  volumes_from:
    - Data
Data:
  image: "busybox:latest"
  volumes:
    - /var/lib/data/postgresql/data:/var/lib/postgresql/data
