on: '2'
services:
  master-data:
    restart: on-failure
    image: "busybox:latest"
    volumes:
      - /var/lib/data/jenkins2:/var/jenkins_home
    entrypoint: tail -F /dev/null
    dns:
      - 8.8.8.8
  master:
    restart: on-failure
    image: "jenkinsci/jenkins:latest"
    ports:
      - "50001:50000"
      - "8081:8080"
    links:
      - master-data
    volumes_from:
      - master-data
    dns:
      - 8.8.8.8
